//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("ModelDebug", "CompetencePersonne", "Competence", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjetFormationDebug.Model.Competence), "Personne", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetFormationDebug.Model.Personne), true)]

#endregion

namespace ProjetFormationDebug.Model
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class ModelDebugContainer : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet ModelDebugContainer à l'aide de la chaîne de connexion trouvée dans la section 'ModelDebugContainer' du fichier de configuration d'application.
        /// </summary>
        public ModelDebugContainer() : base("name=ModelDebugContainer", "ModelDebugContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelDebugContainer.
        /// </summary>
        public ModelDebugContainer(string connectionString) : base(connectionString, "ModelDebugContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelDebugContainer.
        /// </summary>
        public ModelDebugContainer(EntityConnection connection) : base(connection, "ModelDebugContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Competence> Competences
        {
            get
            {
                if ((_Competences == null))
                {
                    _Competences = base.CreateObjectSet<Competence>("Competences");
                }
                return _Competences;
            }
        }
        private ObjectSet<Competence> _Competences;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Personne> Personnes
        {
            get
            {
                if ((_Personnes == null))
                {
                    _Personnes = base.CreateObjectSet<Personne>("Personnes");
                }
                return _Personnes;
            }
        }
        private ObjectSet<Personne> _Personnes;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Competences. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCompetences(Competence competence)
        {
            base.AddObject("Competences", competence);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Personnes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPersonnes(Personne personne)
        {
            base.AddObject("Personnes", personne);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelDebug", Name="Competence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Competence : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Competence.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        /// <param name="libelle">Valeur initiale de la propriété Libelle.</param>
        /// <param name="libelleCourt">Valeur initiale de la propriété LibelleCourt.</param>
        /// <param name="couleur">Valeur initiale de la propriété Couleur.</param>
        public static Competence CreateCompetence(global::System.Int32 id, global::System.String libelle, global::System.String libelleCourt, global::System.String couleur)
        {
            Competence competence = new Competence();
            competence.Id = id;
            competence.Libelle = libelle;
            competence.LibelleCourt = libelleCourt;
            competence.Couleur = couleur;
            return competence;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LibelleCourt
        {
            get
            {
                return _LibelleCourt;
            }
            set
            {
                OnLibelleCourtChanging(value);
                ReportPropertyChanging("LibelleCourt");
                _LibelleCourt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LibelleCourt");
                OnLibelleCourtChanged();
            }
        }
        private global::System.String _LibelleCourt;
        partial void OnLibelleCourtChanging(global::System.String value);
        partial void OnLibelleCourtChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Couleur
        {
            get
            {
                return _Couleur;
            }
            set
            {
                OnCouleurChanging(value);
                ReportPropertyChanging("Couleur");
                _Couleur = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Couleur");
                OnCouleurChanged();
            }
        }
        private global::System.String _Couleur;
        partial void OnCouleurChanging(global::System.String value);
        partial void OnCouleurChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelDebug", "CompetencePersonne", "Personne")]
        public EntityCollection<Personne> Personnes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Personne>("ModelDebug.CompetencePersonne", "Personne");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Personne>("ModelDebug.CompetencePersonne", "Personne", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelDebug", Name="Personne")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Personne : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Personne.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        public static Personne CreatePersonne(global::System.Int32 id)
        {
            Personne personne = new Personne();
            personne.Id = id;
            return personne;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompetenceId
        {
            get
            {
                return _CompetenceId;
            }
            set
            {
                OnCompetenceIdChanging(value);
                ReportPropertyChanging("CompetenceId");
                _CompetenceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompetenceId");
                OnCompetenceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CompetenceId;
        partial void OnCompetenceIdChanging(Nullable<global::System.Int32> value);
        partial void OnCompetenceIdChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelDebug", "CompetencePersonne", "Competence")]
        public Competence Competence
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competence>("ModelDebug.CompetencePersonne", "Competence").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competence>("ModelDebug.CompetencePersonne", "Competence").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Competence> CompetenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competence>("ModelDebug.CompetencePersonne", "Competence");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Competence>("ModelDebug.CompetencePersonne", "Competence", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
